---
title: Unimedia -Etat des services
buildFuture: true
languageCode: fr
defaultContentLanguage: fr
baseURL: https://status.unimedia.fr/
enableGitInfo: true
params:
  categories:
  - name: North Coast
    description: The main servers are located here.
    closed: true
  - name: Empty Category
  - name: Uncategorized
    untitled: true
  systems:
  - name: Gateway
    category: North Coast
  - name: Backup Gateway
    category: North Coast
  - name: Website
    description: The web frontend for the application.
    category: Uncategorized
    link: https://example.com/
  - name: API
    description: The guts of the application.
    category: Uncategorized
  - name: Media Proxy
    description: This is the service responsible for serving images, audio, and video.
      It is reliant on our CDN.
    category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  shortDateFormat: 15:04 UTC — Jan 2
  useRelativeTime: true
  skipSeconds: false
  enableLastMod: true
  useLargeHeaderDesign: false
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  disableDarkMode: false
  useLogo: true
  logo: logo.png
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  disableComplexCalculations: false
  incidentPostsPerPage: "10"
  brand: "#0a0c0f"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"
  alwaysKeepBrandColor: true
  headerTextColor: white
  googleAnalytics: UA-00000000-1
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
  - html
  - json
  section:
  - html
  - json
  - rss
  home:
  - html
  - json
  - rss
  - svg
  term:
  - html
  - json
  - rss
  - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
